name: set_env_from_config_file
description: config env from config file
inputs:
  ENV_PATH_FILE:
    description: "location of config file"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Install yq package"
      shell: bash
      run: |
        sudo apt-get update
        sudo apt install yq
        echo "finished yq package installation" 

    - name: "Config file read"
      shell: bash
      run: |
        echo "${{ inputs.ENV_PATH_FILE }}"
        echo "yq --version"
        PROJECT_ID=yq '.PROJECT_ID' ${{ inputs. ENV_PATH_FILE }}
        
        echo "PROJECT_ID=${PROJECT_ID}" >> $GITHUB_ENV
