name: auth_to_gcp
description: Auth to GCP and get access token

runs:
  using: "composite"
  steps:
    - name: 'authenticate to GCP'
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: "projects/381351396040/locations/global/workloadIdentityPools/github-action-pool/providers/github-action"
        service_account: "gcp-auth-sa@card-service-dev-454416.iam.gserviceaccount.com"
        token_format: "access_token"