name: Create Database
run-name: setting up the new database
on:
  workflow_dispatch
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint. New
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Configure GCP credentials"
        uses: ./.github/actions/auth_to_gcp

      - name: "Configure PG client"
        uses: ./.github/actions/init_pg_client

      - name: "Configure Cloud SQL Proxy"
        uses: ./.github/actions/init_cloudsql_proxy

      - name: "Print Env"
        run: |
          echo ${PGPASSWORD}

      - name: "Run PostgreSQL commands"
        shell: bash
        run: |
          psql -h 127.0.0.1 -d postgres -p 5432 -U postgres -c "SELECT datname FROM pg_database"
