name: Print Secret
run-name: print secrets from GSM
on:
  workflow_dispatch
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint. New
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Configure GCP credentials"
        uses: ./.github/actions/auth_to_gcp

      - name: 'secrets'
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
          secrets: |-
            token: card-service-dev-454416/testSecret

      - name: 'Print'
        run: |
          echo ${{ steps.secrets.outputs.token }}